module SampleModule {
    struct Tag {
        long id;
        string label;
    };
    typedef sequence<Tag> TagList;
    struct Item {
        long id;
        string name;
        TagList tags;
    };
    interface ItemService {
        TagList getTags(in long itemId);
        Item getItem(in long id);
    };
};
